from typing import Protocol

class RetryManager(Protocol):
    def max_attempts(self) -> int: ...
    def should_retry_status(self, status: int) -> bool: ...
    def delay_s(self, attempt: int) -> float: ...
